// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLog = `-- name: CreateAuditLog :one
INSERT INTO audit_log (tenant_id, entity_type, entity_id, action, actor_id, occurred_at, payload_json)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, entity_type, entity_id, action, actor_id, occurred_at, payload_json
`

type CreateAuditLogParams struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	EntityType  string             `json:"entity_type"`
	EntityID    pgtype.UUID        `json:"entity_id"`
	Action      string             `json:"action"`
	ActorID     pgtype.UUID        `json:"actor_id"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
	PayloadJson []byte             `json:"payload_json"`
}

func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.TenantID,
		arg.EntityType,
		arg.EntityID,
		arg.Action,
		arg.ActorID,
		arg.OccurredAt,
		arg.PayloadJson,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EntityType,
		&i.EntityID,
		&i.Action,
		&i.ActorID,
		&i.OccurredAt,
		&i.PayloadJson,
	)
	return i, err
}

const listAuditLogByTenantID = `-- name: ListAuditLogByTenantID :many
SELECT id, tenant_id, entity_type, entity_id, action, actor_id, occurred_at, payload_json
FROM audit_log
WHERE tenant_id = $1
ORDER BY occurred_at DESC, id DESC
LIMIT $2
`

type ListAuditLogByTenantIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Limit    int32       `json:"limit"`
}

func (q *Queries) ListAuditLogByTenantID(ctx context.Context, arg ListAuditLogByTenantIDParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogByTenantID, arg.TenantID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EntityType,
			&i.EntityID,
			&i.Action,
			&i.ActorID,
			&i.OccurredAt,
			&i.PayloadJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
