// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: choirs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChoir = `-- name: CreateChoir :one
INSERT INTO choirs (tenant_id, name, description)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, name, description, active, created_at, updated_at
`

type CreateChoirParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateChoir(ctx context.Context, arg CreateChoirParams) (Choir, error) {
	row := q.db.QueryRow(ctx, createChoir, arg.TenantID, arg.Name, arg.Description)
	var i Choir
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChoirByID = `-- name: GetChoirByID :one
SELECT id, tenant_id, name, description, active, created_at, updated_at
FROM choirs
WHERE tenant_id = $1
  AND id = $2
  AND active = TRUE
`

type GetChoirByIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) GetChoirByID(ctx context.Context, arg GetChoirByIDParams) (Choir, error) {
	row := q.db.QueryRow(ctx, getChoirByID, arg.TenantID, arg.ID)
	var i Choir
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChoirsByTenantID = `-- name: ListChoirsByTenantID :many
SELECT id, tenant_id, name, description, active, created_at, updated_at
FROM choirs
WHERE tenant_id = $1
  AND active = TRUE
ORDER BY name ASC
`

func (q *Queries) ListChoirsByTenantID(ctx context.Context, tenantID pgtype.UUID) ([]Choir, error) {
	rows, err := q.db.Query(ctx, listChoirsByTenantID, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Choir
	for rows.Next() {
		var i Choir
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
