// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: devices.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeviceToken = `-- name: CreateDeviceToken :one
INSERT INTO device_tokens (tenant_id, user_id, platform, token)
VALUES ($1, $2, $3, $4)
ON CONFLICT (tenant_id, token)
DO UPDATE SET
	user_id = EXCLUDED.user_id,
	platform = EXCLUDED.platform,
	active = TRUE,
	updated_at = NOW()
RETURNING id, tenant_id, user_id, platform, token, active, created_at, updated_at
`

type CreateDeviceTokenParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
	Platform string      `json:"platform"`
	Token    string      `json:"token"`
}

func (q *Queries) CreateDeviceToken(ctx context.Context, arg CreateDeviceTokenParams) (DeviceToken, error) {
	row := q.db.QueryRow(ctx, createDeviceToken,
		arg.TenantID,
		arg.UserID,
		arg.Platform,
		arg.Token,
	)
	var i DeviceToken
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Platform,
		&i.Token,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateDeviceTokenByToken = `-- name: DeactivateDeviceTokenByToken :execrows
UPDATE device_tokens
SET active = FALSE,
	updated_at = NOW()
WHERE tenant_id = $1
  AND token = $2
  AND active = TRUE
`

type DeactivateDeviceTokenByTokenParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	Token    string      `json:"token"`
}

func (q *Queries) DeactivateDeviceTokenByToken(ctx context.Context, arg DeactivateDeviceTokenByTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateDeviceTokenByToken, arg.TenantID, arg.Token)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listActiveDeviceTokensByUserID = `-- name: ListActiveDeviceTokensByUserID :many
SELECT id, tenant_id, user_id, platform, token, active, created_at, updated_at
FROM device_tokens
WHERE tenant_id = $1
  AND user_id = $2
  AND active = TRUE
ORDER BY created_at ASC, id ASC
`

type ListActiveDeviceTokensByUserIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) ListActiveDeviceTokensByUserID(ctx context.Context, arg ListActiveDeviceTokensByUserIDParams) ([]DeviceToken, error) {
	rows, err := q.db.Query(ctx, listActiveDeviceTokensByUserID, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeviceToken
	for rows.Next() {
		var i DeviceToken
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Platform,
			&i.Token,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
