// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelEvent = `-- name: CancelEvent :execrows
UPDATE events
SET active = FALSE,
    updated_at = NOW()
WHERE tenant_id = $1
  AND id = $2
  AND active = TRUE
`

type CancelEventParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) CancelEvent(ctx context.Context, arg CancelEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelEvent, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (tenant_id, choir_id, title, description, event_type, location, start_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, choir_id, title, description, event_type, location, start_at, active, created_at, updated_at
`

type CreateEventParams struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	ChoirID     pgtype.UUID        `json:"choir_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	EventType   string             `json:"event_type"`
	Location    pgtype.Text        `json:"location"`
	StartAt     pgtype.Timestamptz `json:"start_at"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.TenantID,
		arg.ChoirID,
		arg.Title,
		arg.Description,
		arg.EventType,
		arg.Location,
		arg.StartAt,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChoirID,
		&i.Title,
		&i.Description,
		&i.EventType,
		&i.Location,
		&i.StartAt,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventByIDForMember = `-- name: GetEventByIDForMember :one
SELECT e.id, e.tenant_id, e.choir_id, e.title, e.description, e.event_type, e.location, e.start_at, e.active, e.created_at, e.updated_at
FROM events AS e
INNER JOIN choir_members AS cm ON cm.choir_id = e.choir_id
WHERE e.tenant_id = $1
  AND e.id = $2
  AND cm.user_id = $3
  AND e.active = TRUE
  AND cm.active = TRUE
`

type GetEventByIDForMemberParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetEventByIDForMember(ctx context.Context, arg GetEventByIDForMemberParams) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByIDForMember, arg.TenantID, arg.ID, arg.UserID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChoirID,
		&i.Title,
		&i.Description,
		&i.EventType,
		&i.Location,
		&i.StartAt,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveChoirMemberUserIDs = `-- name: ListActiveChoirMemberUserIDs :many
SELECT cm.user_id
FROM choir_members AS cm
INNER JOIN users AS u ON u.id = cm.user_id
WHERE cm.tenant_id = $1
  AND cm.choir_id = $2
  AND cm.active = TRUE
  AND u.active = TRUE
ORDER BY cm.user_id
`

type ListActiveChoirMemberUserIDsParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ChoirID  pgtype.UUID `json:"choir_id"`
}

func (q *Queries) ListActiveChoirMemberUserIDs(ctx context.Context, arg ListActiveChoirMemberUserIDsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listActiveChoirMemberUserIDs, arg.TenantID, arg.ChoirID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var user_id pgtype.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByChoirID = `-- name: ListEventsByChoirID :many
SELECT id, tenant_id, choir_id, title, description, event_type, location, start_at, active, created_at, updated_at
FROM events
WHERE tenant_id = $1
  AND choir_id = $2
  AND active = TRUE
ORDER BY start_at ASC, title ASC
`

type ListEventsByChoirIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ChoirID  pgtype.UUID `json:"choir_id"`
}

func (q *Queries) ListEventsByChoirID(ctx context.Context, arg ListEventsByChoirIDParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEventsByChoirID, arg.TenantID, arg.ChoirID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ChoirID,
			&i.Title,
			&i.Description,
			&i.EventType,
			&i.Location,
			&i.StartAt,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events
SET title = $3,
    description = $4,
    event_type = $5,
    location = $6,
    start_at = $7,
    updated_at = NOW()
WHERE tenant_id = $1
  AND id = $2
  AND active = TRUE
RETURNING id, tenant_id, choir_id, title, description, event_type, location, start_at, active, created_at, updated_at
`

type UpdateEventParams struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	ID          pgtype.UUID        `json:"id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	EventType   string             `json:"event_type"`
	Location    pgtype.Text        `json:"location"`
	StartAt     pgtype.Timestamptz `json:"start_at"`
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, updateEvent,
		arg.TenantID,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.EventType,
		arg.Location,
		arg.StartAt,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChoirID,
		&i.Title,
		&i.Description,
		&i.EventType,
		&i.Location,
		&i.StartAt,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
