// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_repertoires.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addRepertoireToEvent = `-- name: AddRepertoireToEvent :one
INSERT INTO event_repertoires (tenant_id, event_id, repertoire_id)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, event_id, repertoire_id, created_at, updated_at
`

type AddRepertoireToEventParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	EventID      pgtype.UUID `json:"event_id"`
	RepertoireID pgtype.UUID `json:"repertoire_id"`
}

func (q *Queries) AddRepertoireToEvent(ctx context.Context, arg AddRepertoireToEventParams) (EventRepertoire, error) {
	row := q.db.QueryRow(ctx, addRepertoireToEvent, arg.TenantID, arg.EventID, arg.RepertoireID)
	var i EventRepertoire
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EventID,
		&i.RepertoireID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRepertoiresByEvent = `-- name: ListRepertoiresByEvent :many
SELECT r.id, r.tenant_id, r.choir_id, r.name, r.description, r.created_at, r.updated_at, r.archived
FROM event_repertoires AS er
INNER JOIN repertoires AS r ON r.id = er.repertoire_id
WHERE er.tenant_id = $1
  AND er.event_id = $2
ORDER BY r.name ASC
`

type ListRepertoiresByEventParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	EventID  pgtype.UUID `json:"event_id"`
}

func (q *Queries) ListRepertoiresByEvent(ctx context.Context, arg ListRepertoiresByEventParams) ([]Repertoire, error) {
	rows, err := q.db.Query(ctx, listRepertoiresByEvent, arg.TenantID, arg.EventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repertoire
	for rows.Next() {
		var i Repertoire
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ChoirID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRepertoireFromEvent = `-- name: RemoveRepertoireFromEvent :execrows
DELETE FROM event_repertoires
WHERE tenant_id = $1
  AND event_id = $2
  AND repertoire_id = $3
`

type RemoveRepertoireFromEventParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	EventID      pgtype.UUID `json:"event_id"`
	RepertoireID pgtype.UUID `json:"repertoire_id"`
}

func (q *Queries) RemoveRepertoireFromEvent(ctx context.Context, arg RemoveRepertoireFromEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeRepertoireFromEvent, arg.TenantID, arg.EventID, arg.RepertoireID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
