// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: files.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createKitFile = `-- name: CreateKitFile :one
INSERT INTO kit_files (id, tenant_id, voice_kit_id, original_filename, stored_filename, content_type, size_bytes, storage_key)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, voice_kit_id, original_filename, stored_filename, content_type, size_bytes, storage_key, active, created_at, updated_at
`

type CreateKitFileParams struct {
	ID               pgtype.UUID `json:"id"`
	TenantID         pgtype.UUID `json:"tenant_id"`
	VoiceKitID       pgtype.UUID `json:"voice_kit_id"`
	OriginalFilename string      `json:"original_filename"`
	StoredFilename   string      `json:"stored_filename"`
	ContentType      string      `json:"content_type"`
	SizeBytes        int64       `json:"size_bytes"`
	StorageKey       string      `json:"storage_key"`
}

func (q *Queries) CreateKitFile(ctx context.Context, arg CreateKitFileParams) (KitFile, error) {
	row := q.db.QueryRow(ctx, createKitFile,
		arg.ID,
		arg.TenantID,
		arg.VoiceKitID,
		arg.OriginalFilename,
		arg.StoredFilename,
		arg.ContentType,
		arg.SizeBytes,
		arg.StorageKey,
	)
	var i KitFile
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.VoiceKitID,
		&i.OriginalFilename,
		&i.StoredFilename,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateKitFile = `-- name: DeactivateKitFile :execrows
UPDATE kit_files
SET active = FALSE,
    updated_at = NOW()
WHERE tenant_id = $1
  AND id = $2
  AND active = TRUE
`

type DeactivateKitFileParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) DeactivateKitFile(ctx context.Context, arg DeactivateKitFileParams) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateKitFile, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getKitFileByIDForMember = `-- name: GetKitFileByIDForMember :one
SELECT kf.id, kf.tenant_id, kf.voice_kit_id, kf.original_filename, kf.stored_filename, kf.content_type, kf.size_bytes,
       kf.storage_key, kf.active, kf.created_at, kf.updated_at, vk.choir_id
FROM kit_files AS kf
INNER JOIN voice_kits AS vk ON vk.id = kf.voice_kit_id
INNER JOIN choir_members AS cm ON cm.choir_id = vk.choir_id
WHERE kf.tenant_id = $1
  AND kf.id = $2
  AND cm.user_id = $3
  AND kf.active = TRUE
  AND vk.active = TRUE
  AND cm.active = TRUE
`

type GetKitFileByIDForMemberParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
	UserID   pgtype.UUID `json:"user_id"`
}

type GetKitFileByIDForMemberRow struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	VoiceKitID       pgtype.UUID        `json:"voice_kit_id"`
	OriginalFilename string             `json:"original_filename"`
	StoredFilename   string             `json:"stored_filename"`
	ContentType      string             `json:"content_type"`
	SizeBytes        int64              `json:"size_bytes"`
	StorageKey       string             `json:"storage_key"`
	Active           bool               `json:"active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	ChoirID          pgtype.UUID        `json:"choir_id"`
}

func (q *Queries) GetKitFileByIDForMember(ctx context.Context, arg GetKitFileByIDForMemberParams) (GetKitFileByIDForMemberRow, error) {
	row := q.db.QueryRow(ctx, getKitFileByIDForMember, arg.TenantID, arg.ID, arg.UserID)
	var i GetKitFileByIDForMemberRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.VoiceKitID,
		&i.OriginalFilename,
		&i.StoredFilename,
		&i.ContentType,
		&i.SizeBytes,
		&i.StorageKey,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ChoirID,
	)
	return i, err
}

const listKitFilesByVoiceKitID = `-- name: ListKitFilesByVoiceKitID :many
SELECT id, tenant_id, voice_kit_id, original_filename, stored_filename, content_type, size_bytes, storage_key, active, created_at, updated_at
FROM kit_files
WHERE tenant_id = $1
  AND voice_kit_id = $2
  AND active = TRUE
ORDER BY created_at ASC, original_filename ASC
`

type ListKitFilesByVoiceKitIDParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	VoiceKitID pgtype.UUID `json:"voice_kit_id"`
}

func (q *Queries) ListKitFilesByVoiceKitID(ctx context.Context, arg ListKitFilesByVoiceKitIDParams) ([]KitFile, error) {
	rows, err := q.db.Query(ctx, listKitFilesByVoiceKitID, arg.TenantID, arg.VoiceKitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KitFile
	for rows.Next() {
		var i KitFile
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.VoiceKitID,
			&i.OriginalFilename,
			&i.StoredFilename,
			&i.ContentType,
			&i.SizeBytes,
			&i.StorageKey,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
