// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: instruments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addInstrumentToUser = `-- name: AddInstrumentToUser :one
INSERT INTO user_instruments (tenant_id, user_id, instrument_id)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, user_id, instrument_id, created_at, updated_at
`

type AddInstrumentToUserParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	UserID       pgtype.UUID `json:"user_id"`
	InstrumentID pgtype.UUID `json:"instrument_id"`
}

func (q *Queries) AddInstrumentToUser(ctx context.Context, arg AddInstrumentToUserParams) (UserInstrument, error) {
	row := q.db.QueryRow(ctx, addInstrumentToUser, arg.TenantID, arg.UserID, arg.InstrumentID)
	var i UserInstrument
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.InstrumentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const archiveInstrument = `-- name: ArchiveInstrument :execrows
UPDATE instruments
SET archived = TRUE,
    updated_at = NOW()
WHERE tenant_id = $1
  AND id = $2
`

type ArchiveInstrumentParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) ArchiveInstrument(ctx context.Context, arg ArchiveInstrumentParams) (int64, error) {
	result, err := q.db.Exec(ctx, archiveInstrument, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createInstrument = `-- name: CreateInstrument :one
INSERT INTO instruments (tenant_id, choir_id, name, description, icon)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, choir_id, name, description, icon, created_at, updated_at, archived
`

type CreateInstrumentParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	ChoirID     pgtype.UUID `json:"choir_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Icon        pgtype.Text `json:"icon"`
}

func (q *Queries) CreateInstrument(ctx context.Context, arg CreateInstrumentParams) (Instrument, error) {
	row := q.db.QueryRow(ctx, createInstrument,
		arg.TenantID,
		arg.ChoirID,
		arg.Name,
		arg.Description,
		arg.Icon,
	)
	var i Instrument
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChoirID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Archived,
	)
	return i, err
}

const getInstrumentByIDForMember = `-- name: GetInstrumentByIDForMember :one
SELECT i.id, i.tenant_id, i.choir_id, i.name, i.description, i.icon, i.created_at, i.updated_at, i.archived
FROM instruments AS i
INNER JOIN choir_members AS cm ON cm.choir_id = i.choir_id
WHERE i.tenant_id = $1
  AND i.id = $2
  AND cm.user_id = $3
  AND cm.active = TRUE
`

type GetInstrumentByIDForMemberParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetInstrumentByIDForMember(ctx context.Context, arg GetInstrumentByIDForMemberParams) (Instrument, error) {
	row := q.db.QueryRow(ctx, getInstrumentByIDForMember, arg.TenantID, arg.ID, arg.UserID)
	var i Instrument
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChoirID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Archived,
	)
	return i, err
}

const listInstrumentsByChoirID = `-- name: ListInstrumentsByChoirID :many
SELECT id, tenant_id, choir_id, name, description, icon, created_at, updated_at, archived
FROM instruments
WHERE tenant_id = $1
  AND choir_id = $2
ORDER BY name ASC
`

type ListInstrumentsByChoirIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ChoirID  pgtype.UUID `json:"choir_id"`
}

func (q *Queries) ListInstrumentsByChoirID(ctx context.Context, arg ListInstrumentsByChoirIDParams) ([]Instrument, error) {
	rows, err := q.db.Query(ctx, listInstrumentsByChoirID, arg.TenantID, arg.ChoirID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Instrument
	for rows.Next() {
		var i Instrument
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ChoirID,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstrumentsByUser = `-- name: ListInstrumentsByUser :many
SELECT i.id, i.tenant_id, i.choir_id, i.name, i.description, i.icon, i.created_at, i.updated_at, i.archived
FROM user_instruments AS ui
INNER JOIN instruments AS i ON i.id = ui.instrument_id
WHERE ui.tenant_id = $1
  AND ui.user_id = $2
ORDER BY i.name ASC
`

type ListInstrumentsByUserParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) ListInstrumentsByUser(ctx context.Context, arg ListInstrumentsByUserParams) ([]Instrument, error) {
	rows, err := q.db.Query(ctx, listInstrumentsByUser, arg.TenantID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Instrument
	for rows.Next() {
		var i Instrument
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ChoirID,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByInstrument = `-- name: ListUsersByInstrument :many
SELECT u.id, u.tenant_id, u.email, u.full_name, u.active, u.created_at, u.updated_at
FROM user_instruments AS ui
INNER JOIN users AS u ON u.id = ui.user_id
WHERE ui.tenant_id = $1
  AND ui.instrument_id = $2
  AND u.active = TRUE
ORDER BY u.full_name ASC
`

type ListUsersByInstrumentParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	InstrumentID pgtype.UUID `json:"instrument_id"`
}

type ListUsersByInstrumentRow struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Email     string             `json:"email"`
	FullName  string             `json:"full_name"`
	Active    bool               `json:"active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListUsersByInstrument(ctx context.Context, arg ListUsersByInstrumentParams) ([]ListUsersByInstrumentRow, error) {
	rows, err := q.db.Query(ctx, listUsersByInstrument, arg.TenantID, arg.InstrumentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersByInstrumentRow
	for rows.Next() {
		var i ListUsersByInstrumentRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Email,
			&i.FullName,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeInstrumentFromUser = `-- name: RemoveInstrumentFromUser :execrows
DELETE FROM user_instruments
WHERE tenant_id = $1
  AND user_id = $2
  AND instrument_id = $3
`

type RemoveInstrumentFromUserParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	UserID       pgtype.UUID `json:"user_id"`
	InstrumentID pgtype.UUID `json:"instrument_id"`
}

func (q *Queries) RemoveInstrumentFromUser(ctx context.Context, arg RemoveInstrumentFromUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeInstrumentFromUser, arg.TenantID, arg.UserID, arg.InstrumentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateInstrument = `-- name: UpdateInstrument :one
UPDATE instruments
SET name = $3,
    description = $4,
    icon = $5,
    updated_at = NOW()
WHERE tenant_id = $1
  AND id = $2
RETURNING id, tenant_id, choir_id, name, description, icon, created_at, updated_at, archived
`

type UpdateInstrumentParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Icon        pgtype.Text `json:"icon"`
}

func (q *Queries) UpdateInstrument(ctx context.Context, arg UpdateInstrumentParams) (Instrument, error) {
	row := q.db.QueryRow(ctx, updateInstrument,
		arg.TenantID,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Icon,
	)
	var i Instrument
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChoirID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Archived,
	)
	return i, err
}
