// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: materials.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addInstrumentToMaterial = `-- name: AddInstrumentToMaterial :one
INSERT INTO material_instruments (tenant_id, material_id, instrument_id)
VALUES ($1, $2, $3)
RETURNING id, tenant_id, material_id, instrument_id, created_at, updated_at
`

type AddInstrumentToMaterialParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	MaterialID   pgtype.UUID `json:"material_id"`
	InstrumentID pgtype.UUID `json:"instrument_id"`
}

func (q *Queries) AddInstrumentToMaterial(ctx context.Context, arg AddInstrumentToMaterialParams) (MaterialInstrument, error) {
	row := q.db.QueryRow(ctx, addInstrumentToMaterial, arg.TenantID, arg.MaterialID, arg.InstrumentID)
	var i MaterialInstrument
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.MaterialID,
		&i.InstrumentID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const archiveMaterial = `-- name: ArchiveMaterial :execrows
UPDATE materials
SET archived = TRUE,
    updated_at = NOW()
WHERE tenant_id = $1
  AND id = $2
`

type ArchiveMaterialParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) ArchiveMaterial(ctx context.Context, arg ArchiveMaterialParams) (int64, error) {
	result, err := q.db.Exec(ctx, archiveMaterial, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createMaterial = `-- name: CreateMaterial :one
INSERT INTO materials (tenant_id, choir_id, song_id, name, material_type, target_type, voice_type)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, tenant_id, choir_id, song_id, name, material_type, target_type, voice_type, archived, created_at, updated_at
`

type CreateMaterialParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	ChoirID      pgtype.UUID `json:"choir_id"`
	SongID       pgtype.UUID `json:"song_id"`
	Name         string      `json:"name"`
	MaterialType string      `json:"material_type"`
	TargetType   string      `json:"target_type"`
	VoiceType    pgtype.Text `json:"voice_type"`
}

func (q *Queries) CreateMaterial(ctx context.Context, arg CreateMaterialParams) (Material, error) {
	row := q.db.QueryRow(ctx, createMaterial,
		arg.TenantID,
		arg.ChoirID,
		arg.SongID,
		arg.Name,
		arg.MaterialType,
		arg.TargetType,
		arg.VoiceType,
	)
	var i Material
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChoirID,
		&i.SongID,
		&i.Name,
		&i.MaterialType,
		&i.TargetType,
		&i.VoiceType,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMaterialByIDForMember = `-- name: GetMaterialByIDForMember :one
SELECT m.id, m.tenant_id, m.choir_id, m.song_id, m.name, m.material_type, m.target_type, m.voice_type, m.archived, m.created_at, m.updated_at
FROM materials AS m
INNER JOIN choir_members AS cm ON cm.choir_id = m.choir_id
WHERE m.tenant_id = $1
  AND m.id = $2
  AND cm.user_id = $3
  AND cm.active = TRUE
`

type GetMaterialByIDForMemberParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetMaterialByIDForMember(ctx context.Context, arg GetMaterialByIDForMemberParams) (Material, error) {
	row := q.db.QueryRow(ctx, getMaterialByIDForMember, arg.TenantID, arg.ID, arg.UserID)
	var i Material
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChoirID,
		&i.SongID,
		&i.Name,
		&i.MaterialType,
		&i.TargetType,
		&i.VoiceType,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listFilesByMaterial = `-- name: ListFilesByMaterial :many
SELECT id, tenant_id, material_id, original_filename, stored_filename, content_type, size_bytes, storage_key, archived, created_at, updated_at
FROM material_files
WHERE tenant_id = $1
  AND material_id = $2
ORDER BY created_at ASC, original_filename ASC
`

type ListFilesByMaterialParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	MaterialID pgtype.UUID `json:"material_id"`
}

func (q *Queries) ListFilesByMaterial(ctx context.Context, arg ListFilesByMaterialParams) ([]MaterialFile, error) {
	rows, err := q.db.Query(ctx, listFilesByMaterial, arg.TenantID, arg.MaterialID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MaterialFile
	for rows.Next() {
		var i MaterialFile
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.MaterialID,
			&i.OriginalFilename,
			&i.StoredFilename,
			&i.ContentType,
			&i.SizeBytes,
			&i.StorageKey,
			&i.Archived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInstrumentsByMaterial = `-- name: ListInstrumentsByMaterial :many
SELECT i.id, i.tenant_id, i.choir_id, i.name, i.description, i.icon, i.archived, i.created_at, i.updated_at
FROM material_instruments AS mi
INNER JOIN instruments AS i ON i.id = mi.instrument_id
WHERE mi.tenant_id = $1
  AND mi.material_id = $2
ORDER BY i.name ASC
`

type ListInstrumentsByMaterialParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	MaterialID pgtype.UUID `json:"material_id"`
}

type ListInstrumentsByMaterialRow struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	ChoirID     pgtype.UUID        `json:"choir_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Icon        pgtype.Text        `json:"icon"`
	Archived    bool               `json:"archived"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListInstrumentsByMaterial(ctx context.Context, arg ListInstrumentsByMaterialParams) ([]ListInstrumentsByMaterialRow, error) {
	rows, err := q.db.Query(ctx, listInstrumentsByMaterial, arg.TenantID, arg.MaterialID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInstrumentsByMaterialRow
	for rows.Next() {
		var i ListInstrumentsByMaterialRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ChoirID,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.Archived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaterialsByChoirID = `-- name: ListMaterialsByChoirID :many
SELECT id, tenant_id, choir_id, song_id, name, material_type, target_type, voice_type, archived, created_at, updated_at
FROM materials
WHERE tenant_id = $1
  AND choir_id = $2
ORDER BY name ASC
`

type ListMaterialsByChoirIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ChoirID  pgtype.UUID `json:"choir_id"`
}

func (q *Queries) ListMaterialsByChoirID(ctx context.Context, arg ListMaterialsByChoirIDParams) ([]Material, error) {
	rows, err := q.db.Query(ctx, listMaterialsByChoirID, arg.TenantID, arg.ChoirID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Material
	for rows.Next() {
		var i Material
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ChoirID,
			&i.SongID,
			&i.Name,
			&i.MaterialType,
			&i.TargetType,
			&i.VoiceType,
			&i.Archived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaterialsBySongID = `-- name: ListMaterialsBySongID :many
SELECT id, tenant_id, choir_id, song_id, name, material_type, target_type, voice_type, archived, created_at, updated_at
FROM materials
WHERE tenant_id = $1
  AND song_id = $2
ORDER BY name ASC
`

type ListMaterialsBySongIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	SongID   pgtype.UUID `json:"song_id"`
}

func (q *Queries) ListMaterialsBySongID(ctx context.Context, arg ListMaterialsBySongIDParams) ([]Material, error) {
	rows, err := q.db.Query(ctx, listMaterialsBySongID, arg.TenantID, arg.SongID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Material
	for rows.Next() {
		var i Material
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ChoirID,
			&i.SongID,
			&i.Name,
			&i.MaterialType,
			&i.TargetType,
			&i.VoiceType,
			&i.Archived,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeInstrumentFromMaterial = `-- name: RemoveInstrumentFromMaterial :execrows
DELETE FROM material_instruments
WHERE tenant_id = $1
  AND material_id = $2
  AND instrument_id = $3
`

type RemoveInstrumentFromMaterialParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	MaterialID   pgtype.UUID `json:"material_id"`
	InstrumentID pgtype.UUID `json:"instrument_id"`
}

func (q *Queries) RemoveInstrumentFromMaterial(ctx context.Context, arg RemoveInstrumentFromMaterialParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeInstrumentFromMaterial, arg.TenantID, arg.MaterialID, arg.InstrumentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateMaterial = `-- name: UpdateMaterial :one
UPDATE materials
SET name = $3,
    material_type = $4,
    target_type = $5,
    voice_type = $6,
    updated_at = NOW()
WHERE tenant_id = $1
  AND id = $2
RETURNING id, tenant_id, choir_id, song_id, name, material_type, target_type, voice_type, archived, created_at, updated_at
`

type UpdateMaterialParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	ID           pgtype.UUID `json:"id"`
	Name         string      `json:"name"`
	MaterialType string      `json:"material_type"`
	TargetType   string      `json:"target_type"`
	VoiceType    pgtype.Text `json:"voice_type"`
}

func (q *Queries) UpdateMaterial(ctx context.Context, arg UpdateMaterialParams) (Material, error) {
	row := q.db.QueryRow(ctx, updateMaterial,
		arg.TenantID,
		arg.ID,
		arg.Name,
		arg.MaterialType,
		arg.TargetType,
		arg.VoiceType,
	)
	var i Material
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChoirID,
		&i.SongID,
		&i.Name,
		&i.MaterialType,
		&i.TargetType,
		&i.VoiceType,
		&i.Archived,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
