// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memberships.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createChoirMember = `-- name: CreateChoirMember :one
INSERT INTO choir_members (tenant_id, choir_id, user_id, role)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, choir_id, user_id, role, active, created_at, updated_at
`

type CreateChoirMemberParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ChoirID  pgtype.UUID `json:"choir_id"`
	UserID   pgtype.UUID `json:"user_id"`
	Role     string      `json:"role"`
}

func (q *Queries) CreateChoirMember(ctx context.Context, arg CreateChoirMemberParams) (ChoirMember, error) {
	row := q.db.QueryRow(ctx, createChoirMember,
		arg.TenantID,
		arg.ChoirID,
		arg.UserID,
		arg.Role,
	)
	var i ChoirMember
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChoirID,
		&i.UserID,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChoirMemberByChoirAndUser = `-- name: GetChoirMemberByChoirAndUser :one
SELECT id, tenant_id, choir_id, user_id, role, active, created_at, updated_at
FROM choir_members
WHERE tenant_id = $1
  AND choir_id = $2
  AND user_id = $3
  AND active = TRUE
`

type GetChoirMemberByChoirAndUserParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ChoirID  pgtype.UUID `json:"choir_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetChoirMemberByChoirAndUser(ctx context.Context, arg GetChoirMemberByChoirAndUserParams) (ChoirMember, error) {
	row := q.db.QueryRow(ctx, getChoirMemberByChoirAndUser, arg.TenantID, arg.ChoirID, arg.UserID)
	var i ChoirMember
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChoirID,
		&i.UserID,
		&i.Role,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChoirMembersByChoirID = `-- name: ListChoirMembersByChoirID :many
SELECT cm.id, cm.tenant_id, cm.choir_id, cm.user_id, cm.role, cm.active, cm.created_at, cm.updated_at,
       u.email, u.full_name
FROM choir_members AS cm
INNER JOIN users AS u ON u.id = cm.user_id
WHERE cm.tenant_id = $1
  AND cm.choir_id = $2
  AND cm.active = TRUE
  AND u.active = TRUE
ORDER BY u.full_name ASC, u.email ASC
`

type ListChoirMembersByChoirIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ChoirID  pgtype.UUID `json:"choir_id"`
}

type ListChoirMembersByChoirIDRow struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	ChoirID   pgtype.UUID        `json:"choir_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Role      string             `json:"role"`
	Active    bool               `json:"active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Email     string             `json:"email"`
	FullName  string             `json:"full_name"`
}

func (q *Queries) ListChoirMembersByChoirID(ctx context.Context, arg ListChoirMembersByChoirIDParams) ([]ListChoirMembersByChoirIDRow, error) {
	rows, err := q.db.Query(ctx, listChoirMembersByChoirID, arg.TenantID, arg.ChoirID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChoirMembersByChoirIDRow
	for rows.Next() {
		var i ListChoirMembersByChoirIDRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ChoirID,
			&i.UserID,
			&i.Role,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.FullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
