// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditLog struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	EntityType  string             `json:"entity_type"`
	EntityID    pgtype.UUID        `json:"entity_id"`
	Action      string             `json:"action"`
	ActorID     pgtype.UUID        `json:"actor_id"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
	PayloadJson []byte             `json:"payload_json"`
}

type Choir struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Active      bool               `json:"active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type ChoirMember struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	ChoirID   pgtype.UUID        `json:"choir_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Role      string             `json:"role"`
	Active    bool               `json:"active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type DeviceToken struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Platform  string             `json:"platform"`
	Token     string             `json:"token"`
	Active    bool               `json:"active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Event struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	ChoirID     pgtype.UUID        `json:"choir_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	EventType   string             `json:"event_type"`
	Location    pgtype.Text        `json:"location"`
	StartAt     pgtype.Timestamptz `json:"start_at"`
	Active      bool               `json:"active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type EventRepertoire struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	EventID      pgtype.UUID        `json:"event_id"`
	RepertoireID pgtype.UUID        `json:"repertoire_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Instrument struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	ChoirID     pgtype.UUID        `json:"choir_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Icon        pgtype.Text        `json:"icon"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Archived    bool               `json:"archived"`
}

type Material struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	ChoirID      pgtype.UUID        `json:"choir_id"`
	SongID       pgtype.UUID        `json:"song_id"`
	Name         string             `json:"name"`
	MaterialType string             `json:"material_type"`
	TargetType   string             `json:"target_type"`
	VoiceType    pgtype.Text        `json:"voice_type"`
	Archived     bool               `json:"archived"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type MaterialFile struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	MaterialID       pgtype.UUID        `json:"material_id"`
	OriginalFilename string             `json:"original_filename"`
	StoredFilename   string             `json:"stored_filename"`
	ContentType      string             `json:"content_type"`
	SizeBytes        int64              `json:"size_bytes"`
	StorageKey       string             `json:"storage_key"`
	Archived         bool               `json:"archived"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type MaterialInstrument struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	MaterialID   pgtype.UUID        `json:"material_id"`
	InstrumentID pgtype.UUID        `json:"instrument_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Repertoire struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	ChoirID     pgtype.UUID        `json:"choir_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Archived    bool               `json:"archived"`
}

type RepertoireSong struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	RepertoireID   pgtype.UUID        `json:"repertoire_id"`
	SongID         pgtype.UUID        `json:"song_id"`
	ExecutionOrder int32              `json:"execution_order"`
	Notes          pgtype.Text        `json:"notes"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type ScheduledNotification struct {
	ID                  pgtype.UUID        `json:"id"`
	TenantID            pgtype.UUID        `json:"tenant_id"`
	EventID             pgtype.UUID        `json:"event_id"`
	UserID              pgtype.UUID        `json:"user_id"`
	ReminderType        string             `json:"reminder_type"`
	ScheduledFor        pgtype.Timestamptz `json:"scheduled_for"`
	Status              string             `json:"status"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	Attempts            int32              `json:"attempts"`
	LastError           pgtype.Text        `json:"last_error"`
	ProcessingStartedAt pgtype.Timestamptz `json:"processing_started_at"`
	SentAt              pgtype.Timestamptz `json:"sent_at"`
}

type Song struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	ChoirID   pgtype.UUID        `json:"choir_id"`
	Title     string             `json:"title"`
	Composer  pgtype.Text        `json:"composer"`
	Arranger  pgtype.Text        `json:"arranger"`
	SongKey   pgtype.Text        `json:"song_key"`
	Duration  pgtype.Text        `json:"duration"`
	Notes     pgtype.Text        `json:"notes"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Archived  bool               `json:"archived"`
}

type Tenant struct {
	ID          pgtype.UUID        `json:"id"`
	Slug        string             `json:"slug"`
	DisplayName string             `json:"display_name"`
	Active      bool               `json:"active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type TenantConfig struct {
	TenantID       pgtype.UUID        `json:"tenant_id"`
	LogoUrl        pgtype.Text        `json:"logo_url"`
	PrimaryColor   pgtype.Text        `json:"primary_color"`
	SecondaryColor pgtype.Text        `json:"secondary_color"`
	CustomDomain   pgtype.Text        `json:"custom_domain"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	Email        string             `json:"email"`
	FullName     string             `json:"full_name"`
	Active       bool               `json:"active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	PasswordHash pgtype.Text        `json:"password_hash"`
}

type UserInstrument struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	InstrumentID pgtype.UUID        `json:"instrument_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
