// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimDueScheduledNotifications = `-- name: ClaimDueScheduledNotifications :many
WITH due AS (
	SELECT id
	FROM scheduled_notifications AS sn
	WHERE (
		sn.status = 'pending'
		AND sn.scheduled_for <= $1
	) OR (
		sn.status = 'processing'
		AND sn.processing_started_at IS NOT NULL
		AND sn.processing_started_at <= $2
	)
	ORDER BY sn.scheduled_for ASC, sn.created_at ASC
	LIMIT $3
	FOR UPDATE SKIP LOCKED
)
UPDATE scheduled_notifications AS sn
SET status = 'processing',
	processing_started_at = $1,
	updated_at = NOW()
FROM due
WHERE sn.id = due.id
RETURNING sn.id, sn.tenant_id, sn.event_id, sn.user_id, sn.reminder_type, sn.scheduled_for, sn.status,
	sn.attempts, sn.last_error, sn.processing_started_at, sn.sent_at, sn.created_at, sn.updated_at
`

type ClaimDueScheduledNotificationsParams struct {
	ProcessingStartedAt   pgtype.Timestamptz `json:"processing_started_at"`
	ProcessingStartedAt_2 pgtype.Timestamptz `json:"processing_started_at_2"`
	Limit                 int32              `json:"limit"`
}

type ClaimDueScheduledNotificationsRow struct {
	ID                  pgtype.UUID        `json:"id"`
	TenantID            pgtype.UUID        `json:"tenant_id"`
	EventID             pgtype.UUID        `json:"event_id"`
	UserID              pgtype.UUID        `json:"user_id"`
	ReminderType        string             `json:"reminder_type"`
	ScheduledFor        pgtype.Timestamptz `json:"scheduled_for"`
	Status              string             `json:"status"`
	Attempts            int32              `json:"attempts"`
	LastError           pgtype.Text        `json:"last_error"`
	ProcessingStartedAt pgtype.Timestamptz `json:"processing_started_at"`
	SentAt              pgtype.Timestamptz `json:"sent_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ClaimDueScheduledNotifications(ctx context.Context, arg ClaimDueScheduledNotificationsParams) ([]ClaimDueScheduledNotificationsRow, error) {
	rows, err := q.db.Query(ctx, claimDueScheduledNotifications, arg.ProcessingStartedAt, arg.ProcessingStartedAt_2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimDueScheduledNotificationsRow
	for rows.Next() {
		var i ClaimDueScheduledNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EventID,
			&i.UserID,
			&i.ReminderType,
			&i.ScheduledFor,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.ProcessingStartedAt,
			&i.SentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const failScheduledNotification = `-- name: FailScheduledNotification :execrows
UPDATE scheduled_notifications
SET status = 'failed',
	attempts = attempts + 1,
	last_error = $4,
	processing_started_at = NULL,
	updated_at = NOW()
WHERE tenant_id = $1
	AND id = $2
	AND status = 'processing'
	AND processing_started_at = $3
`

type FailScheduledNotificationParams struct {
	TenantID            pgtype.UUID        `json:"tenant_id"`
	ID                  pgtype.UUID        `json:"id"`
	ProcessingStartedAt pgtype.Timestamptz `json:"processing_started_at"`
	LastError           pgtype.Text        `json:"last_error"`
}

func (q *Queries) FailScheduledNotification(ctx context.Context, arg FailScheduledNotificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, failScheduledNotification,
		arg.TenantID,
		arg.ID,
		arg.ProcessingStartedAt,
		arg.LastError,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markScheduledNotificationInvalidToken = `-- name: MarkScheduledNotificationInvalidToken :execrows
UPDATE scheduled_notifications
SET status = 'invalid_token',
	attempts = attempts + 1,
	last_error = $4,
	processing_started_at = NULL,
	updated_at = NOW()
WHERE tenant_id = $1
	AND id = $2
	AND status = 'processing'
	AND processing_started_at = $3
`

type MarkScheduledNotificationInvalidTokenParams struct {
	TenantID            pgtype.UUID        `json:"tenant_id"`
	ID                  pgtype.UUID        `json:"id"`
	ProcessingStartedAt pgtype.Timestamptz `json:"processing_started_at"`
	LastError           pgtype.Text        `json:"last_error"`
}

func (q *Queries) MarkScheduledNotificationInvalidToken(ctx context.Context, arg MarkScheduledNotificationInvalidTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, markScheduledNotificationInvalidToken,
		arg.TenantID,
		arg.ID,
		arg.ProcessingStartedAt,
		arg.LastError,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markScheduledNotificationSent = `-- name: MarkScheduledNotificationSent :execrows
UPDATE scheduled_notifications
SET status = 'sent',
	attempts = attempts + 1,
	last_error = NULL,
	processing_started_at = NULL,
	sent_at = $4,
	updated_at = NOW()
WHERE tenant_id = $1
	AND id = $2
	AND status = 'processing'
	AND processing_started_at = $3
`

type MarkScheduledNotificationSentParams struct {
	TenantID            pgtype.UUID        `json:"tenant_id"`
	ID                  pgtype.UUID        `json:"id"`
	ProcessingStartedAt pgtype.Timestamptz `json:"processing_started_at"`
	SentAt              pgtype.Timestamptz `json:"sent_at"`
}

func (q *Queries) MarkScheduledNotificationSent(ctx context.Context, arg MarkScheduledNotificationSentParams) (int64, error) {
	result, err := q.db.Exec(ctx, markScheduledNotificationSent,
		arg.TenantID,
		arg.ID,
		arg.ProcessingStartedAt,
		arg.SentAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retryScheduledNotification = `-- name: RetryScheduledNotification :execrows
UPDATE scheduled_notifications
SET status = 'pending',
	attempts = attempts + 1,
	scheduled_for = $4,
	last_error = $5,
	processing_started_at = NULL,
	updated_at = NOW()
WHERE tenant_id = $1
	AND id = $2
	AND status = 'processing'
	AND processing_started_at = $3
`

type RetryScheduledNotificationParams struct {
	TenantID            pgtype.UUID        `json:"tenant_id"`
	ID                  pgtype.UUID        `json:"id"`
	ProcessingStartedAt pgtype.Timestamptz `json:"processing_started_at"`
	ScheduledFor        pgtype.Timestamptz `json:"scheduled_for"`
	LastError           pgtype.Text        `json:"last_error"`
}

func (q *Queries) RetryScheduledNotification(ctx context.Context, arg RetryScheduledNotificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, retryScheduledNotification,
		arg.TenantID,
		arg.ID,
		arg.ProcessingStartedAt,
		arg.ScheduledFor,
		arg.LastError,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
