// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: repertoires.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addSongToRepertoire = `-- name: AddSongToRepertoire :one
INSERT INTO repertoire_songs (tenant_id, repertoire_id, song_id, execution_order, notes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, repertoire_id, song_id, execution_order, notes, created_at, updated_at
`

type AddSongToRepertoireParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	RepertoireID   pgtype.UUID `json:"repertoire_id"`
	SongID         pgtype.UUID `json:"song_id"`
	ExecutionOrder int32       `json:"execution_order"`
	Notes          pgtype.Text `json:"notes"`
}

func (q *Queries) AddSongToRepertoire(ctx context.Context, arg AddSongToRepertoireParams) (RepertoireSong, error) {
	row := q.db.QueryRow(ctx, addSongToRepertoire,
		arg.TenantID,
		arg.RepertoireID,
		arg.SongID,
		arg.ExecutionOrder,
		arg.Notes,
	)
	var i RepertoireSong
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.RepertoireID,
		&i.SongID,
		&i.ExecutionOrder,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const archiveRepertoire = `-- name: ArchiveRepertoire :execrows
UPDATE repertoires
SET archived = TRUE,
    updated_at = NOW()
WHERE tenant_id = $1
  AND id = $2
`

type ArchiveRepertoireParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) ArchiveRepertoire(ctx context.Context, arg ArchiveRepertoireParams) (int64, error) {
	result, err := q.db.Exec(ctx, archiveRepertoire, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createRepertoire = `-- name: CreateRepertoire :one
INSERT INTO repertoires (tenant_id, choir_id, name, description)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, choir_id, name, description, created_at, updated_at, archived
`

type CreateRepertoireParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	ChoirID     pgtype.UUID `json:"choir_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateRepertoire(ctx context.Context, arg CreateRepertoireParams) (Repertoire, error) {
	row := q.db.QueryRow(ctx, createRepertoire,
		arg.TenantID,
		arg.ChoirID,
		arg.Name,
		arg.Description,
	)
	var i Repertoire
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChoirID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Archived,
	)
	return i, err
}

const getRepertoireByIDForMember = `-- name: GetRepertoireByIDForMember :one
SELECT r.id, r.tenant_id, r.choir_id, r.name, r.description, r.created_at, r.updated_at, r.archived
FROM repertoires AS r
INNER JOIN choir_members AS cm ON cm.choir_id = r.choir_id
WHERE r.tenant_id = $1
  AND r.id = $2
  AND cm.user_id = $3
  AND cm.active = TRUE
`

type GetRepertoireByIDForMemberParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetRepertoireByIDForMember(ctx context.Context, arg GetRepertoireByIDForMemberParams) (Repertoire, error) {
	row := q.db.QueryRow(ctx, getRepertoireByIDForMember, arg.TenantID, arg.ID, arg.UserID)
	var i Repertoire
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChoirID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Archived,
	)
	return i, err
}

const listRepertoiresByChoirID = `-- name: ListRepertoiresByChoirID :many
SELECT id, tenant_id, choir_id, name, description, created_at, updated_at, archived
FROM repertoires
WHERE tenant_id = $1
  AND choir_id = $2
ORDER BY name ASC
`

type ListRepertoiresByChoirIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ChoirID  pgtype.UUID `json:"choir_id"`
}

func (q *Queries) ListRepertoiresByChoirID(ctx context.Context, arg ListRepertoiresByChoirIDParams) ([]Repertoire, error) {
	rows, err := q.db.Query(ctx, listRepertoiresByChoirID, arg.TenantID, arg.ChoirID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Repertoire
	for rows.Next() {
		var i Repertoire
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ChoirID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSongsByRepertoire = `-- name: ListSongsByRepertoire :many
SELECT s.id, s.tenant_id, s.choir_id, s.title, s.composer, s.arranger, s.song_key, s.duration, s.notes, s.created_at, s.updated_at, s.archived, rs.execution_order, rs.notes AS repertoire_notes
FROM repertoire_songs AS rs
INNER JOIN songs AS s ON s.id = rs.song_id
WHERE rs.tenant_id = $1
  AND rs.repertoire_id = $2
ORDER BY rs.execution_order ASC, s.title ASC
`

type ListSongsByRepertoireParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	RepertoireID pgtype.UUID `json:"repertoire_id"`
}

type ListSongsByRepertoireRow struct {
	ID              pgtype.UUID        `json:"id"`
	TenantID        pgtype.UUID        `json:"tenant_id"`
	ChoirID         pgtype.UUID        `json:"choir_id"`
	Title           string             `json:"title"`
	Composer        pgtype.Text        `json:"composer"`
	Arranger        pgtype.Text        `json:"arranger"`
	SongKey         pgtype.Text        `json:"song_key"`
	Duration        pgtype.Text        `json:"duration"`
	Notes           pgtype.Text        `json:"notes"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Archived        bool               `json:"archived"`
	ExecutionOrder  int32              `json:"execution_order"`
	RepertoireNotes pgtype.Text        `json:"repertoire_notes"`
}

func (q *Queries) ListSongsByRepertoire(ctx context.Context, arg ListSongsByRepertoireParams) ([]ListSongsByRepertoireRow, error) {
	rows, err := q.db.Query(ctx, listSongsByRepertoire, arg.TenantID, arg.RepertoireID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSongsByRepertoireRow
	for rows.Next() {
		var i ListSongsByRepertoireRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ChoirID,
			&i.Title,
			&i.Composer,
			&i.Arranger,
			&i.SongKey,
			&i.Duration,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Archived,
			&i.ExecutionOrder,
			&i.RepertoireNotes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeSongFromRepertoire = `-- name: RemoveSongFromRepertoire :execrows
DELETE FROM repertoire_songs
WHERE tenant_id = $1
  AND repertoire_id = $2
  AND song_id = $3
`

type RemoveSongFromRepertoireParams struct {
	TenantID     pgtype.UUID `json:"tenant_id"`
	RepertoireID pgtype.UUID `json:"repertoire_id"`
	SongID       pgtype.UUID `json:"song_id"`
}

func (q *Queries) RemoveSongFromRepertoire(ctx context.Context, arg RemoveSongFromRepertoireParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeSongFromRepertoire, arg.TenantID, arg.RepertoireID, arg.SongID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRepertoire = `-- name: UpdateRepertoire :one
UPDATE repertoires
SET name = $3,
    description = $4,
    updated_at = NOW()
WHERE tenant_id = $1
  AND id = $2
RETURNING id, tenant_id, choir_id, name, description, created_at, updated_at, archived
`

type UpdateRepertoireParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateRepertoire(ctx context.Context, arg UpdateRepertoireParams) (Repertoire, error) {
	row := q.db.QueryRow(ctx, updateRepertoire,
		arg.TenantID,
		arg.ID,
		arg.Name,
		arg.Description,
	)
	var i Repertoire
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChoirID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Archived,
	)
	return i, err
}

const updateRepertoireSongOrder = `-- name: UpdateRepertoireSongOrder :execrows
UPDATE repertoire_songs
SET execution_order = $4,
    updated_at = NOW()
WHERE tenant_id = $1
  AND repertoire_id = $2
  AND song_id = $3
`

type UpdateRepertoireSongOrderParams struct {
	TenantID       pgtype.UUID `json:"tenant_id"`
	RepertoireID   pgtype.UUID `json:"repertoire_id"`
	SongID         pgtype.UUID `json:"song_id"`
	ExecutionOrder int32       `json:"execution_order"`
}

func (q *Queries) UpdateRepertoireSongOrder(ctx context.Context, arg UpdateRepertoireSongOrderParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateRepertoireSongOrder,
		arg.TenantID,
		arg.RepertoireID,
		arg.SongID,
		arg.ExecutionOrder,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
