// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: scheduled_notifications.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelPendingScheduledNotificationsByEventID = `-- name: CancelPendingScheduledNotificationsByEventID :execrows
UPDATE scheduled_notifications
SET status = 'canceled',
    updated_at = NOW()
WHERE tenant_id = $1
  AND event_id = $2
  AND status = 'pending'
`

type CancelPendingScheduledNotificationsByEventIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	EventID  pgtype.UUID `json:"event_id"`
}

func (q *Queries) CancelPendingScheduledNotificationsByEventID(ctx context.Context, arg CancelPendingScheduledNotificationsByEventIDParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelPendingScheduledNotificationsByEventID, arg.TenantID, arg.EventID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createScheduledNotification = `-- name: CreateScheduledNotification :one
INSERT INTO scheduled_notifications (tenant_id, event_id, user_id, reminder_type, scheduled_for, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, event_id, user_id, reminder_type, scheduled_for, status, attempts, last_error, processing_started_at, sent_at, created_at, updated_at
`

type CreateScheduledNotificationParams struct {
	TenantID     pgtype.UUID        `json:"tenant_id"`
	EventID      pgtype.UUID        `json:"event_id"`
	UserID       pgtype.UUID        `json:"user_id"`
	ReminderType string             `json:"reminder_type"`
	ScheduledFor pgtype.Timestamptz `json:"scheduled_for"`
	Status       string             `json:"status"`
}

type CreateScheduledNotificationRow struct {
	ID                  pgtype.UUID        `json:"id"`
	TenantID            pgtype.UUID        `json:"tenant_id"`
	EventID             pgtype.UUID        `json:"event_id"`
	UserID              pgtype.UUID        `json:"user_id"`
	ReminderType        string             `json:"reminder_type"`
	ScheduledFor        pgtype.Timestamptz `json:"scheduled_for"`
	Status              string             `json:"status"`
	Attempts            int32              `json:"attempts"`
	LastError           pgtype.Text        `json:"last_error"`
	ProcessingStartedAt pgtype.Timestamptz `json:"processing_started_at"`
	SentAt              pgtype.Timestamptz `json:"sent_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateScheduledNotification(ctx context.Context, arg CreateScheduledNotificationParams) (CreateScheduledNotificationRow, error) {
	row := q.db.QueryRow(ctx, createScheduledNotification,
		arg.TenantID,
		arg.EventID,
		arg.UserID,
		arg.ReminderType,
		arg.ScheduledFor,
		arg.Status,
	)
	var i CreateScheduledNotificationRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.EventID,
		&i.UserID,
		&i.ReminderType,
		&i.ScheduledFor,
		&i.Status,
		&i.Attempts,
		&i.LastError,
		&i.ProcessingStartedAt,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listScheduledNotificationsByEventID = `-- name: ListScheduledNotificationsByEventID :many
SELECT id, tenant_id, event_id, user_id, reminder_type, scheduled_for, status, attempts, last_error, processing_started_at, sent_at, created_at, updated_at
FROM scheduled_notifications
WHERE tenant_id = $1
  AND event_id = $2
ORDER BY scheduled_for ASC, reminder_type ASC, user_id ASC
`

type ListScheduledNotificationsByEventIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	EventID  pgtype.UUID `json:"event_id"`
}

type ListScheduledNotificationsByEventIDRow struct {
	ID                  pgtype.UUID        `json:"id"`
	TenantID            pgtype.UUID        `json:"tenant_id"`
	EventID             pgtype.UUID        `json:"event_id"`
	UserID              pgtype.UUID        `json:"user_id"`
	ReminderType        string             `json:"reminder_type"`
	ScheduledFor        pgtype.Timestamptz `json:"scheduled_for"`
	Status              string             `json:"status"`
	Attempts            int32              `json:"attempts"`
	LastError           pgtype.Text        `json:"last_error"`
	ProcessingStartedAt pgtype.Timestamptz `json:"processing_started_at"`
	SentAt              pgtype.Timestamptz `json:"sent_at"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListScheduledNotificationsByEventID(ctx context.Context, arg ListScheduledNotificationsByEventIDParams) ([]ListScheduledNotificationsByEventIDRow, error) {
	rows, err := q.db.Query(ctx, listScheduledNotificationsByEventID, arg.TenantID, arg.EventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScheduledNotificationsByEventIDRow
	for rows.Next() {
		var i ListScheduledNotificationsByEventIDRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.EventID,
			&i.UserID,
			&i.ReminderType,
			&i.ScheduledFor,
			&i.Status,
			&i.Attempts,
			&i.LastError,
			&i.ProcessingStartedAt,
			&i.SentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
