// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: songs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveSong = `-- name: ArchiveSong :execrows
UPDATE songs
SET archived = TRUE,
    updated_at = NOW()
WHERE tenant_id = $1
  AND id = $2
`

type ArchiveSongParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) ArchiveSong(ctx context.Context, arg ArchiveSongParams) (int64, error) {
	result, err := q.db.Exec(ctx, archiveSong, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createSong = `-- name: CreateSong :one
INSERT INTO songs (tenant_id, choir_id, title, composer, arranger, song_key, duration, notes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, tenant_id, choir_id, title, composer, arranger, song_key, duration, notes, created_at, updated_at, archived
`

type CreateSongParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ChoirID  pgtype.UUID `json:"choir_id"`
	Title    string      `json:"title"`
	Composer pgtype.Text `json:"composer"`
	Arranger pgtype.Text `json:"arranger"`
	SongKey  pgtype.Text `json:"song_key"`
	Duration pgtype.Text `json:"duration"`
	Notes    pgtype.Text `json:"notes"`
}

func (q *Queries) CreateSong(ctx context.Context, arg CreateSongParams) (Song, error) {
	row := q.db.QueryRow(ctx, createSong,
		arg.TenantID,
		arg.ChoirID,
		arg.Title,
		arg.Composer,
		arg.Arranger,
		arg.SongKey,
		arg.Duration,
		arg.Notes,
	)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChoirID,
		&i.Title,
		&i.Composer,
		&i.Arranger,
		&i.SongKey,
		&i.Duration,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Archived,
	)
	return i, err
}

const getSongByIDForMember = `-- name: GetSongByIDForMember :one
SELECT s.id, s.tenant_id, s.choir_id, s.title, s.composer, s.arranger, s.song_key, s.duration, s.notes, s.created_at, s.updated_at, s.archived
FROM songs AS s
INNER JOIN choir_members AS cm ON cm.choir_id = s.choir_id
WHERE s.tenant_id = $1
  AND s.id = $2
  AND cm.user_id = $3
  AND cm.active = TRUE
`

type GetSongByIDForMemberParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetSongByIDForMember(ctx context.Context, arg GetSongByIDForMemberParams) (Song, error) {
	row := q.db.QueryRow(ctx, getSongByIDForMember, arg.TenantID, arg.ID, arg.UserID)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChoirID,
		&i.Title,
		&i.Composer,
		&i.Arranger,
		&i.SongKey,
		&i.Duration,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Archived,
	)
	return i, err
}

const listSongsByChoirID = `-- name: ListSongsByChoirID :many
SELECT id, tenant_id, choir_id, title, composer, arranger, song_key, duration, notes, created_at, updated_at, archived
FROM songs
WHERE tenant_id = $1
  AND choir_id = $2
ORDER BY title ASC
`

type ListSongsByChoirIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ChoirID  pgtype.UUID `json:"choir_id"`
}

func (q *Queries) ListSongsByChoirID(ctx context.Context, arg ListSongsByChoirIDParams) ([]Song, error) {
	rows, err := q.db.Query(ctx, listSongsByChoirID, arg.TenantID, arg.ChoirID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Song
	for rows.Next() {
		var i Song
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ChoirID,
			&i.Title,
			&i.Composer,
			&i.Arranger,
			&i.SongKey,
			&i.Duration,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSong = `-- name: UpdateSong :one
UPDATE songs
SET title = $3,
    composer = $4,
    arranger = $5,
    song_key = $6,
    duration = $7,
    notes = $8,
    updated_at = NOW()
WHERE tenant_id = $1
  AND id = $2
RETURNING id, tenant_id, choir_id, title, composer, arranger, song_key, duration, notes, created_at, updated_at, archived
`

type UpdateSongParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
	Title    string      `json:"title"`
	Composer pgtype.Text `json:"composer"`
	Arranger pgtype.Text `json:"arranger"`
	SongKey  pgtype.Text `json:"song_key"`
	Duration pgtype.Text `json:"duration"`
	Notes    pgtype.Text `json:"notes"`
}

func (q *Queries) UpdateSong(ctx context.Context, arg UpdateSongParams) (Song, error) {
	row := q.db.QueryRow(ctx, updateSong,
		arg.TenantID,
		arg.ID,
		arg.Title,
		arg.Composer,
		arg.Arranger,
		arg.SongKey,
		arg.Duration,
		arg.Notes,
	)
	var i Song
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChoirID,
		&i.Title,
		&i.Composer,
		&i.Arranger,
		&i.SongKey,
		&i.Duration,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Archived,
	)
	return i, err
}
