// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getTenantByCustomDomain = `-- name: GetTenantByCustomDomain :one
SELECT t.id, t.slug, t.display_name, t.active, t.created_at, t.updated_at
FROM tenants AS t
INNER JOIN tenant_configs AS tc ON tc.tenant_id = t.id
WHERE tc.custom_domain = $1
  AND t.active = TRUE
`

func (q *Queries) GetTenantByCustomDomain(ctx context.Context, customDomain pgtype.Text) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByCustomDomain, customDomain)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, slug, display_name, active, created_at, updated_at
FROM tenants
WHERE slug = $1
  AND active = TRUE
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
