// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: voice_kits.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVoiceKit = `-- name: CreateVoiceKit :one
INSERT INTO voice_kits (tenant_id, choir_id, name, description)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, choir_id, name, description, active, created_at, updated_at
`

type CreateVoiceKitParams struct {
	TenantID    pgtype.UUID `json:"tenant_id"`
	ChoirID     pgtype.UUID `json:"choir_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) CreateVoiceKit(ctx context.Context, arg CreateVoiceKitParams) (VoiceKit, error) {
	row := q.db.QueryRow(ctx, createVoiceKit,
		arg.TenantID,
		arg.ChoirID,
		arg.Name,
		arg.Description,
	)
	var i VoiceKit
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChoirID,
		&i.Name,
		&i.Description,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateVoiceKit = `-- name: DeactivateVoiceKit :execrows
UPDATE voice_kits
SET active = FALSE,
    updated_at = NOW()
WHERE tenant_id = $1
  AND id = $2
  AND active = TRUE
`

type DeactivateVoiceKitParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) DeactivateVoiceKit(ctx context.Context, arg DeactivateVoiceKitParams) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateVoiceKit, arg.TenantID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getVoiceKitByIDForMember = `-- name: GetVoiceKitByIDForMember :one
SELECT vk.id, vk.tenant_id, vk.choir_id, vk.name, vk.description, vk.active, vk.created_at, vk.updated_at
FROM voice_kits AS vk
INNER JOIN choir_members AS cm ON cm.choir_id = vk.choir_id
WHERE vk.tenant_id = $1
  AND vk.id = $2
  AND cm.user_id = $3
  AND vk.active = TRUE
  AND cm.active = TRUE
`

type GetVoiceKitByIDForMemberParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ID       pgtype.UUID `json:"id"`
	UserID   pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetVoiceKitByIDForMember(ctx context.Context, arg GetVoiceKitByIDForMemberParams) (VoiceKit, error) {
	row := q.db.QueryRow(ctx, getVoiceKitByIDForMember, arg.TenantID, arg.ID, arg.UserID)
	var i VoiceKit
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.ChoirID,
		&i.Name,
		&i.Description,
		&i.Active,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVoiceKitsByChoirID = `-- name: ListVoiceKitsByChoirID :many
SELECT id, tenant_id, choir_id, name, description, active, created_at, updated_at
FROM voice_kits
WHERE tenant_id = $1
  AND choir_id = $2
  AND active = TRUE
ORDER BY name ASC
`

type ListVoiceKitsByChoirIDParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	ChoirID  pgtype.UUID `json:"choir_id"`
}

func (q *Queries) ListVoiceKitsByChoirID(ctx context.Context, arg ListVoiceKitsByChoirIDParams) ([]VoiceKit, error) {
	rows, err := q.db.Query(ctx, listVoiceKitsByChoirID, arg.TenantID, arg.ChoirID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VoiceKit
	for rows.Next() {
		var i VoiceKit
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.ChoirID,
			&i.Name,
			&i.Description,
			&i.Active,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
